### ISSUE TITLE
v4: Typescript type missing

### ISSUE THREAD

**Issue by lightofyou** [pmndrs/zustand#1076]
I follow the new Typescipt doc and use the curring to make the type work. But it is still show any.
Bellow is the code.
```
import create from "zustand";

import createAStore, { IExample1Store } from "./store1";
import createBStore, { IExample2Store } from './store2'

export type MyState = IExample1Store & IExample2Store;

const useStore = create<MyState>()((set, get) => ({
  ...createAStore(set, get),
  ...createBStore(set, get)
}));

export default useStore;
```
```
import { GetState, SetState } from "zustand";
import produce from 'immer'
import useAsync from '@/utils/useAsync'
import { mockFetch } from '@/api/example/mockFetch';
import { MyState } from "./index";

export interface IExample1Store {
  dataA: any
  getDataAAction: () => void
}

type StoreFunction = (set: SetState<MyState>, get: GetState<MyState>) => IExample1Store

const createAStore: StoreFunction = (set, get) => ({
  dataA: '',
  getDataAAction: async () => {
    const [result, error] = await useAsync(mockFetch(1))
    if (error) {
      return
    }
    set(produce(state => { state.dataA = result.data }))
  }
});

export default createAStore;
```
```
import { GetState, SetState } from "zustand";
import produce from 'immer'
import useAsync from '@/utils/useAsync'
import { mockFetch } from '@/api/example/mockFetch';
import { MyState } from "./index";

export interface IExample2Store {
  dataB: any
  getDataBAction: () => void
}

type StoreFunction = (set: SetState<MyState>, get: GetState<MyState>) => IExample2Store

const createBStore: StoreFunction = (set, get) => ({
  dataB: '',
  getDataBAction: async () => {
    const [result, error] = await useAsync(mockFetch(2))
    if (error) {
      return
    }
    set(produce(state => { state.dataB = result.data }))
  }
});

export default createBStore;
```

useStore and the state both show any type.
sad

**Comment by dai-shi** [comment]
@devanshj can you please help here?

**Comment by devanshj** [comment]
Follow recipe given [here](https://github.com/pmndrs/zustand/blob/main/docs/typescript.md#independent-slices-pattern) for slices pattern.

---

A tip for you @dai-shi: 99% of TypeScript issues (as you might have noticed) will be because of not following the guide... So first you'd want to check if they have followed the guide, if you find they have not then you can simply redirect them to it and you won't need my help. But if they have indeed followed the guide and yet there are typescript problems then it's the 1% where I can chime in. You see types are even more mathematical than programs, and hence they can be even more "complete". Zustand types are quite complete, it'll be extremely rare that an actual issue pops up :)

I don't mind helping out just making it easy for you to triage and resolve issues. If you wish, you can also keep an issue template at the end of which you'd ask them to tick a checkbox "I have read the [TypeScript guide](https://github.com/pmndrs/zustand/blob/main/docs/typescript.md)".

**Comment by dai-shi** [comment]
> will be because of not following the guide...

I saw the OP says "I follow the new Typescipt doc", so that was my triage and redirect to you.

> it's the 1% where I can chime in.

We might need some other collaborator for 99% triage.

> You see types are even more mathematical than programs, and hence they can be even more "complete". Zustand types are quite complete, it'll be extremely rare that an actual issue pops up :)

I'd like to point out a misconception. While the completeness is important, developer experience is something different. (like, if an equation in math (or how to use it) is not understandable to many users, it's less useful.)
So, I'd like to ask for help with your brain, if there's anything we could do on our end. Not to specific to this issue, but how to reduce 99% issues of TS usage. My naive idea is JSDoc for example, but you may have some better ideas.

> I don't mind helping out most of the times, just making it easy for you to triage and resolve issues.

Thanks for your help always. I try to triage issues before redirecting to you.

> If you wish, you can also keep an issue template at the end of which you'd ask them to tick a checkbox "I have read the [TypeScript guide](https://github.com/pmndrs/zustand/blob/main/docs/typescript.md)".

Hm, yeah, such an issue template can help reducing issues reported.

**Comment by lightofyou** [comment]
> Follow recipe given [here](https://github.com/pmndrs/zustand/blob/main/docs/typescript.md#independent-slices-pattern) for slices pattern.

@devanshj 
I copy the guide code to my demo. But the useStore and the state are still 'any' type.
I wonder if there is an online example on codesandbox?

**Comment by Cuppachino** [comment]
> 
Just made one. Here you go: https://codesandbox.io/s/q3d9nq?file=/src/store/useFruit.ts

**Comment by dai-shi** [comment]
> But I think you are saying that the DX should be good without users having to read the docs

Yes, you get it correctly.

> there's not much we can do about it

(yeah, but then type completeness is not so attractive. but we don't look back. let's do what we can do.)

> 1. Update all code samples in the readme and everywhere to use TS instead of JS

I have thought about this too. I'm a  bit hesitant. Let me re-consider this later.

> 2. Export minimum number of types. For instance we're exporting `GetState` and `SetState`, it's possible the user is trying to write their own `StateCreator` (as the OP did) but doesn't notice it's already available. I think we should deprecate `GetState` and `SetState` with a jsdoc like "You might be looking for `StateCreator`, if not then use `StoreApi<T>['getState']` instead".

This sounds very good. As I said, I don't want to drop types in v4, but deprecating them is fine (and drop it in v5).
Can you open a PR for this?

> 3. (As I already mentioned) Add an issue template at the end of which you'd ask them to tick a checkbox "I have read the [TypeScript guide](https://github.com/pmndrs/zustand/blob/main/docs/typescript.md)".

Yes, this should help. I just think we should have more checkboxes in the template not just this one, which requires to think more.

> 4. The errors can be hard to read, to help with that we can...
>   i. Make a section of frequently encountered errors, what they mean and how to fix them

Sounds good. If we have TS FAQs, it's even easier to have that in the issue template.

>   ii. Create a linter for zustand that has these frequent errors and their fix

we have a linter for valtio. I find it a bit difficult to let many users know it... (so, docs issue again)

> 5. Explore showing custom errors like [this](https://twitter.com/devanshj__/status/1516757450182909959) if possible.

:eyes:

> 6. Add detailed jsdocs for types. For example the jsdoc of `StateCreator` should include what the type is for, what all parameters it takes, what they mean and an example usage.

This sounds good too. I hope somehow we can catch double parens `create()()` pitfall. would be difficult to catch unexpected `any`...

In general, I think I overlooked about jsdocs (because I don't use it very often personally). Now, as I see, people would read jsdoc before `docs` in repo, it would make much sense to add detaild jsdocs.

**Comment by dai-shi** [comment]
I understand your suggestion, but I'd like to keep it as is in v4.
What I could do is add a note for TS users at the beginning of readme, just a small mitigation.

**Comment by lightofyou** [comment]
I really appreciate everyone's help! I found it was a bug of my vs code editor。

> @devanshj I copy the guide code to my demo. But the useStore and the state are still 'any' type. I wonder if there is an online example on codesandbox?

The guide code is ok, after i update my vs code
