### ISSUE TITLE
types error after update to zustand rc1 => rc2

### ISSUE THREAD

**Issue by dohomi** [pmndrs/zustand#1107]
Hello

I used rc1 for a while without an issue. After updating to rc2 all my functions where I am using `shallow` are breaking:

```
const villages = useStore(state => state.villages, shallow)

TS2322: Type 'Village[]' is not assignable to type 'Record<string, unknown>'.   Index signature for type 'string' is missing in type 'Village[]'.
```
Are there additional steps necessary to make this work?

**Comment by dai-shi** [comment]
Thanks for reporting. This is due to #1070.

Though, I think your case should be supported.
Can this be reproduced with typescript playground?

https://tsplay.dev/W4P0OW

Yeah, it does reproduce...

**Comment by dohomi** [comment]
Yes this is the issue - seems to be introduced after rc2

**Comment by devanshj** [comment]
@dai-shi It's best to revert #1070 because there's no good way to express "plain objects" (ie JSON) in a type. For instance you might expect the following to compile, but it doesn't...

```ts
interface Village { name: string }
let x: Record<string, unknown> = {} as Village
//  ~
// Type 'Village' is not assignable to type 'Record<string, unknown>'.
//   Index signature for type 'string' is missing in type 'Village'.
```

Because typescript looks for an actual index signature in `Village`.

But the following does, because type aliases can't have index signatures, only interfaces can...

```ts
type Village = { name: string }
let x: Record<string, unknown> = {} as Village
```

And apparently the following also does (even though `any` is no different than `unknown` here as `string` is subtype of both)...

```ts
interface Village { name: string }
let x: Record<string, any> = {} as Village
```

So #1108 compiles because you changed `unknown` to `any`.

Moreover #1070 itself is also not too great, because it allows non-plain-objects on a deeper level, that is the following still compiles when you'd not want it to...

```ts
import shallow from 'zustand/shallow'

shallow(new Date(), new Date()) // doesn't compile, good
shallow({ a: new Date() }, { a: new Date() }) // compiles, bad
```

The closest we can get with correctly typing `shallow` is the following...

```ts
type JsonOrFunction =
  | string | number | boolean | symbol | bigint | null | undefined
  | { [_ in string | number]: JsonOrFunction }
  | JsonOrFunction[]
  | ((...a: never[]) => unknown)

declare const shallow:
  (a: JsonOrFunction, b: JsonOrFunction) => boolean

shallow(new Date(), new Date()) // doesn't compile, good
shallow({ a: new Date() }, { a: new Date() }) // doesn't compile, good

interface Village { name: string }
shallow({} as Village, {} as Village) // doesn't compile, bad
```

But that again doesn't work for interfaces, so it's best to leave `shallow` simply as...

```ts
declare const shallow: (a: unknown, b: unknown) => boolean
```

And as you said in #1064 it's good to deprecate it for better shallow comparators out there.

**Comment by dai-shi** [comment]
@devanshj Thanks for the explanation!

> It's best to revert #1070 because there's no good way to express "plain objects" (ie JSON) in a type.

I'm not trying to express plain objects.

> But the following does compile because type aliases can't have index signatures, only interfaces can...

Isn't it the other way around? Anyway, thanks for remind about the difference.

> And apparently the following also does compile (even though `any` is no different than `unknown` here as `string` is subtype of both)...
> 
> ```ts
> interface Village { name: string }
> let x: Record<string, any> = {} as Village
> ```

It's interesting that `any` and `unknown` makes difference for index signatures.

> So #1108 compiles because you changed `unknown` to `any`.

So, isn't it a valid technique/workaround to support interfaces?

> Moreover #1070 itself is also not too great, because it allows non-plain-objects on a deeper level, that is the following still compiles when you'd not want it to...
> 
> ```ts
> import shallow from 'zustand/shallow'
> 
> shallow(new Date(), new Date()) // doesn't compile, good
> shallow({ a: new Date() }, { a: new Date() }) // compiles, bad
> ```

No, it's intentional. The second one can compile, which is fine.

> And as you said in #1064 it's good to deprecate it for better shallow comparators out there that compare dates, `{}` vs `[]` etc.

Yeah, I will think about deprecating it before v5.
For now, I think #1108 is something I expect fine. While it's not precise typing, it should cover say 90% of current use cases. 10% may contain false positives, but it's okay.

**Comment by devanshj** [comment]
> No, it's intentional. The second one can compile, which is fine.

Ah okay I missed the fact `a` here will be an object, so the user can't expect `shallow({ a: new Date() }, { a: new Date() })` to return `true` as it's a shallow comparison.

Actually I did realise later that it's only "shallow" comparison and not deep (so it need not be plain deeply), in that case yes #1108 is fine and `Record<string, any>` is an acceptable workaround.

> Isn't it the other way around?

Actually I just checked you can define index signatures in both, I was under impression the following won't compile but it does. Nonetheless the subtyping does get affected based on type alias vs interface.

```ts
type Village = {
  name: string
  [x: string]: string
}
```

**Comment by dohomi** [comment]
@dai-shi this seems not to be fully covered yet. Here I can have still a typing interference issue:

import create from 'zustand'
import shallow from "zustand/shallow";

type RefetchState = {
    refetchTimestamp: string
}
export const useRefetchState = create<RefetchState>()(set => ({
    refetchTimestamp: ''
}))

export const useRefetchTimestamp = () => useRefetchState(state => state.refetchTimestamp, shallow)
// ERROR: TS2322: Type 'string' is not assignable to type 'Record<string, any>'.

**Comment by dai-shi** [comment]
hm, function overload doesn't work for us.. will look into it. thanks for reporting.

**Comment by devanshj** [comment]
Haven't checked (afk) but probably the issue is that TS infers `U` from the second argument instead of the (return type of) first argument (weirdly enough). So we can tell TS to only infer `U` from the selector...

```diff
- (selector: (t: T) => U, equals: (a: U, b: U) => boolean) => U
+ (selector: (t: T) => U, equals: (a: NoInfer<U>, b: NoInfer<U>) => boolean) => U

+ type NoInfer<T> = [T][T extends unknown ? 0 : never]
```

But I think it's better to stay away from overloads and #1117 is good. (Moreover afaict I think overloads were not even needed in the first place.)

**Comment by dai-shi** [comment]
(yeah, it's convincing that I finally did just a simplification from v3 version in #1117.)

**Comment by qingzhoufeihu** [comment]
import create from 'zustand'
import shallow from "zustand/shallow";

type RefetchState = {
    refetchTimestamp: string
}
export const useRefetchState = create<RefetchState>()(set => ({
    refetchTimestamp: ''
}))

export const useRefetchTimestamp = () => useRefetchState(state => state.refetchTimestamp, shallow)
// ERROR: TS2322: Type 'string' is not assignable to type 'Record<string, any>'.
