### ISSUE TITLE
Typescript devtools named store typing issue

### ISSUE THREAD

**Issue by vollmerr** [pmndrs/zustand#1205]
Typescript gives the following error for named devtool stores, for example from the docs `devtools(store, {name: "MyStore"})`

```
Argument of type '{ name: string; }' is not assignable to parameter of type 'DevtoolsOptions'
```

Looks like the types from @redux-devtools/extension are not being pulled in due to it being a dev dependency, adding @redux-devtools/extension as an additional dependency to my project solves the issue.

Example:
https://stackblitz.com/edit/react-ts-ktahyv?file=store.ts

Using zustand version 4.1.0

**Comment by dai-shi** [comment]
Thanks for reporting. This is the change in #1200.
I forgot about the fact that users need to install the package.
We have two options:
1. Update the doc to tell that we need to install the package. (peerDeps might not be a good solution.)
2. Revert #1200, and fix types (meaning we copy&paste types from the package.)

@devanshj any advice on this?

**Comment by devanshj** [comment]
How about we add an actual dependency in the package.json?

Other than that I think either of the two options you mentioned would do, just that install manually could be a bit annoying.

Another thing you could try using triple-slash references... So instead of writing `import type { Config } from '@redux-devtools/extension'` you could write `/// <reference types="@redux-devtools/extension"/>` but I'm not sure if it'll work or if it'll still require user to install `@redux-devtools/extension`.

**Comment by dai-shi** [comment]
We don't want a dependency. I'll try option 2.

**Comment by dai-shi** [comment]
@vollmerr Could you try if #1207 fixes your case?
https://ci.codesandbox.io/status/pmndrs/zustand/pr/1207
☝️ Find "Local Install Instructions"
