### ISSUE TITLE
zustand 4.1.2 create() initializer type problems with store mutators

### ISSUE THREAD

**Issue by scatterfish** [pmndrs/zustand#1368]
I have a function that extracts out the initializer for a store to a function so that I can create many variants of a particular store, in this case various cache stores.

I was previously working with zustand 4.1.1 and the only type errors that I had were the getter and setter possibly being undefined, so I could suppress them using assertions.

After updating to zustand 4.1.2, there are now new type errors that prevent building, and I cannot for the life of me figure out what's going on with them.

I made a [minimal CodeSandbox demo of the problem available here](https://codesandbox.io/s/zustand-create-initializer-with-storemutator-problem-zer3y6?file=/src/App.tsx).

A possibly notable observation is that without the `M` parameter, the type of `set` is reported to be `(partial: Cache<K, V> | Partial<Cache<K, V>> | ((state: Cache<K, V>) => Cache<K, V> | Partial<Cache<K, V>>), replace?: boolean | undefined) => void`.

With the `M` parameter, it instead becomes `Get<Mutate<StoreApi<Cache<K, V>>, M>, "setState", undefined>`.

The closest I've gotten to figuring out a possible cause is that the `Get` type might not be inferring that the `"setState"` and `"getState"` fields should (I think) be guaranteed to be present, but that's really just grasping at straws.

**Comment by dai-shi** [comment]
Interesting. I can't reproduce the error in typescript playground: https://tsplay.dev/mbQv4N

(how can we change the typescript version in codesandbox?)

**Comment by scatterfish** [comment]
I edited the `package.json` file to use 4.8.4 as the TypeScript version, so if you want to use some other version you can change that value.

**Comment by dai-shi** [comment]
https://codesandbox.io/s/zustand-create-initializer-with-storemutator-problem-forked-zs900n?file=/src/App.tsx
It still shows errors with TS 4.7.4.

**Comment by scatterfish** [comment]
You're right. It seems like what actually causes the new type errors is updating from zustand 4.1.1 to 4.1.2

**Comment by dai-shi** [comment]
https://codesandbox.io/s/zustand-create-initializer-with-storemutator-problem-forked-477063?file=/src/App.tsx
Downgrading to v4.1.1 changes it.
So, #1348 must be related.
We need to ask @devanshj for help. It's weird that TS playground doesn't repro. Hope it does..

**Comment by dai-shi** [comment]
@scatterfish Can you update the issue title and description please?

**Comment by devanshj** [comment]
Long post ahead, if you're looking for just a fix, the codesandbox with the fix is linked at the very end.

This behavior is kinda correct, let me first build a minimal repro...

```ts
import create, { StateCreator, StoreMutatorIdentifier } from "zustand"
import { persist } from "zustand/middleware"

interface State
  { count: number
  , increment: () => void
  }

const foo: <M extends [StoreMutatorIdentifier, unknown][]>() => StateCreator<State, M> =
  () => (set, get) => ({
    count: 0,
    increment: () => {
      // @ts-expect-error
      set({ count: get().count + 1 })
    }
  })

create<State>()(persist(foo()))
```

Here it is wrong to expect `get` to be `StoreApi<State>["getState"]` and `set` to be `StoreApi<State>["setState"]`... Why? Because they can be anything, `M` will decide what they'll be, it's possible they are `42` for if `M` is `[["troll", never]]`...

```ts
import create, { StoreApi, Mutate, StateCreator, StoreMutatorIdentifier } from "zustand"
import { persist } from "zustand/middleware"

declare module 'zustand' {
  interface StoreMutators<S, A> {
    troll: Omit<S, "getState" | "setState"> & { getState: 42, setState: 42 }
  }
}

export const troll = ((f: any) => (_: any, __: any, store: any) => {
  store.getState = 42
  store.setState = 42
  return f(store.getState, store.setState, store)
}) as unknown as
  < T extends State
  , Mps extends [StoreMutatorIdentifier, unknown][] = []
  , Mcs extends [StoreMutatorIdentifier, unknown][] = []
  >
    (f: StateCreator<T, [...Mps, ['troll', never]], Mcs>) =>
      StateCreator<T, Mps, [['troll', never], ...Mcs]>

interface State
  { count: number
  , increment: () => void
  }

const foo: <M extends [StoreMutatorIdentifier, unknown][]>() => StateCreator<State, M> =
  () => (set, get) => ({
    count: 0,
    increment: () => {
      set({ count: get().count + 1 })
    }
  })

create<State>()(persist(troll(foo())))
```

Surely we don't want this code to compile, and it doesn't. So the previous code also doesn't compile because of the same reason... What `foo` is claiming in it's type is false, it's saying I can work with any mutators `M`, well if that is true then why do you make assumptions about `M` in your implementation that it'll not contain `["troll", never]`? So the correct type of `foo` is this...

```ts
import create, { StateCreator } from "zustand"
import { persist } from "zustand/middleware"

interface State
  { count: number
  , increment: () => void
  }

const foo: () => StateCreator<State, []> =
  () => (set, get) => ({
    count: 0,
    increment: () => {
      set({ count: get().count + 1 })
    }
  })

create<State>()(persist(foo()))
//                      ~~~~~
// Type '[["zustand/persist", unknown]]' is not assignable to type '[]'
```

Now `foo` is honest, it accepts that it can't implement the state creator for all store types, it can implement the state creator as long as the store type is a subset of `StoreApi<State>`, but now we have this new type error.

This is were we've hit the limitation of how we encode mutations...

```ts
import { StoreMutatorIdentifier, StoreApi, Mutate } from "zustand"

let test0: StateCreatorActual<State, [["zustand/persist", unknown]]> =
  {} as StateCreatorActual<State, []>
// compiles

let test1: StateCreatorWithPhantom<State, [["zustand/persist", unknown]]> =
  {} as StateCreatorWithPhantom<State, []>
// doesn't compile
// Types of parameters '$$storeMutations' and '$$storeMutations' are incompatible.
//   Type '[["zustand/persist", unknown]]' is not assignable to type '[]'.

type StateCreatorActual<
  T,
  Mis extends [StoreMutatorIdentifier, unknown][] = [],
  Mos extends [StoreMutatorIdentifier, unknown][] = [],
  U = T
> =
  & (
      ( setState: Get<Mutate<StoreApi<T>, Mis>, "setState", undefined>
      , getState: Get<Mutate<StoreApi<T>, Mis>, "getState", undefined>
      , store: Mutate<StoreApi<T>, Mis>
      // , $$storeMutations: Mis
      ) => U
    )
  & { $$storeMutators?: Mos }

// same as `StateCreator` from zustand
type StateCreatorWithPhantom<
  T,
  Mis extends [StoreMutatorIdentifier, unknown][] = [],
  Mos extends [StoreMutatorIdentifier, unknown][] = [],
  U = T
> =
  & (
      ( setState: Get<Mutate<StoreApi<T>, Mis>, "setState", undefined>
      , getState: Get<Mutate<StoreApi<T>, Mis>, "getState", undefined>
      , store: Mutate<StoreApi<T>, Mis>
      , $$storeMutations: Mis
      ) => U
    )
  & { $$storeMutators?: Mos }

type Get<T, K, F> =
  K extends keyof T ? T[K] : F

interface State
  { count: number
  , increment: () => void
  }
```

So we can see that `StateCreator<State, []>` actually is a subtype of `StateCreator<State, [["zustand/persist", unknown]]>` but because of our phantom `$$storeMutations` it no longer is a subtype that hence our code does not compile.

I'll see if I can remove that phantom parameter and improve the subtyping relation, but for now you'd have to make an assertion...

```ts
import create, { StateCreator } from "zustand"
import { persist } from "zustand/middleware"

interface State
  { count: number
  , increment: () => void
  }

const foo: () => StateCreator<State, []> =
  () => (set, get) => ({
    count: 0,
    increment: () => {
      set({ count: get().count + 1 })
    }
  })

create<State>()(persist(foo() as unknown as StateCreator<State, [["zustand/persist", unknown]]>))
```

Or if you want to be a bit fancy then...

```ts
const assertMutators =
  <Mis extends [StoreMutatorIdentifier, unknown][]>() =>
    <T, Mos extends [StoreMutatorIdentifier, unknown][]>(f: StateCreator<T, any, Mos>) =>
      f as unknown as StateCreator<T, Mis, Mos>

// ...

let x = create<State>()(persist(assertMutators<[["zustand/persist", unknown]]>()(foo())))
```

Also keep in mind that `["troll, never]` was an extreme example, it could also have been more realistic for example a mutator that mutates the store in a way that `foo` which assumes the mutators to be `[]` breaks. If we want unsoundness to be caught then the types should not lie. Ie if we are truthful in `foo`'s type and use `[]`, then when `foo()` is used with `troll` it will be caught but if we're not truthful in `foo`'s type and use a generic `M`, then it won't be caught...

```ts
import create, { StoreApi, Mutate, StateCreator, StoreMutatorIdentifier } from "zustand"
import { persist } from "zustand/middleware"

declare module 'zustand' {
  interface StoreMutators<S, A> {
    troll: Omit<S, "getState" | "setState"> & { getState: 42, setState: 42 }
  }
}

export const troll = ((f: any) => (_: any, __: any, store: any) => {
  store.getState = 42
  store.setState = 42
  return f(store.getState, store.setState, store)
}) as unknown as
  < T extends State
  , Mps extends [StoreMutatorIdentifier, unknown][] = []
  , Mcs extends [StoreMutatorIdentifier, unknown][] = []
  >
    (f: StateCreator<T, [...Mps, ['troll', never]], Mcs>) =>
      StateCreator<T, Mps, [['troll', never], ...Mcs]>

interface State
  { count: number
  , increment: () => void
  }

const fooTruthful: () => StateCreator<State, []> =
  () => (set, get) => ({
    count: 0,
    increment: () => {
      set({ count: get().count + 1 })
    }
  })


const fooLying: <M extends [StoreMutatorIdentifier, unknown][]>() => StateCreator<State, M> =
  () => (set, get) => ({
    count: 0,
    increment: () => {
      // @ts-ignore
      set({ count: get().count + 1 })
    }
  })

create<State>()(persist(troll(fooLying())))
// compiles

create<State>()(persist(troll(fooTruthful())))
//                            ~~~~~~~~~~~~~
// does not compile
// Types of parameters 'setState' and 'setState' are incompatible.
//   Type 'number' is not assignable to type '(partial: State | Partial<State> | ((state: State) => State | Partial<State>), replace?: boolean | undefined) => void'
```

Now ofc if one doesn't want to aim for such soundness and wishes to make using `foo` more convenient ie without requiring a type assertion at the caller then they can indeed lie in the type and make an assertion in the implementation, that's also not a big deal I guess...

```ts
const foo = <M extends [StoreMutatorIdentifier, unknown][]>() => {
  let f: StateCreator<State, []> = (set, get) => ({
    count: 0,
    increment: () => {
      set({ count: get().count + 1 })
    }
  })
  return f as unknown as StateCreator<State, M>
}

create<State>()(persist(foo())) // compiles
create<State>()(troll(foo())) // also compiles
```

So if there's an gaurantee outside the type system that you will always use middlewares in your codebase that never mutate the store in a way it's no longer a subtype of the vanilla store, then sure you can use the generic `M extends [StoreMutatorIdentifier, unknown][]>` because now there's an implicit gaurantee that `Mutate<StoreApi<unknown>, M>` will always be a subtype of `Mutate<StoreApi<unknown>, []>` always hold. This is indeed true for all middlewares zustand exports, but it's not true for middlewares in general, they can do whatever they want.

Now another the problem is that the types of `get`, `set` and even `store` in `foo` that has the generic `M` are not correct... Both in `4.1.1` and in `4.1.2`... They are more weird in `4.1.2`, not sure why but it's not important as the types are wrong anyway... all three parameters should be `unknown`. Because they are literally unknown, `M` can be anything it could even make the whole store 
`42` not just `getState` or `setState`... xD

```ts
declare module 'zustand' {
  interface StoreMutators<S, A> {
    troll: 42
  }
}
```

(Also, technically the current types are correct, ie they are "generic" which is indeed like `unknown` but they later get resolved it to something concrete which we don't want).

So I'll open a PR to fix this, instead of `unknown` get could make an empty interface that acts like unknown but has some documentation...

```
/**
 * You're writing an implementation that works with all mutators,
 * in most cases this is not possible hence you've stumble upon
 * this unknown type. See #1368 issue for more.
 * Most likely you want to make them concrete to set a minimum
 * contraint.
 */
interface UnknownBecauseOfGenericMutators {}
```

And now in `foo`, `get`, `set` and `store` would become of type `UnknownBecauseOfGenericMutators`. I'm not sure if this is a breaking change or not, but this is indeed the correct change, we can discuss whether we want to have this or not in the PR.

Another option is if zustand declares that it's types assume that the all store mutators mutate the store in a way that they remain a subtype of the vanilla store, then in that case if we come across a generic `M` instead of making the parameters `unknown`, we can make them of the vanilla store as that's the minimum gaurantee. But note that here invovles a bit of lie, the type system is not aware of this implicit constriant on mutators, but still not a big deal and doable. And we probably can't make the contraint explicit in the type system.

And note that usually all middlewares would have to mutate to preserve the subtype with `StoreApi<unknown>` or else the store won't work with things like [`useStore`](https://github.com/pmndrs/zustand/blob/d27ea948843b2c955ce2be530e5e963dff8958de/src/react.ts#L23-L31) etc.

So let me know @dai-shi, what you prefer out of these two options...
1. No implicit contraints, store mutators can mutate store anyhow, make all parameters of `StateCreator<unknown, [StoreMutatorIdentifier, unknown][]>` as `UnknownBecauseOfGenericMutators`.
2. Implicict contraints, store mutators can only mutate the store in a way it remains a subtype of `StoreApi<unknown>`, make parameters of `StateCreator<unknown, [StoreMutatorIdentifier, unknown][]>` same as `StoreCreator<unknown, []>`.

So to summarize...
- The type of `foo` is not correct (given zustand does not have any restrictions on mutators as of today). The implementation assumes that `get` and `set` would be a subtype of the vanilla store, so this must be reflected in the type.
- The type errors when typing `foo` with a generic `M` are not helpful, we'll either make them better if we go with option 1 or you'll no longer see those errors if we go with option 2.
- `StateCreator` type has a limitation because `StateCreator<unknown, []>` is not a subtype of `StateCreator<unknown, [["zustand/persist", unknown]]` but when in fact it should be a subtype. I'll probably open a PR to experiment a fix I had in mind if we go with option 1. But it won't be required at least in this case if we go with option 2.

The two ways to solve the OP issue....
- Make `getTestCacheInitializer` not use generic `M` and make an type assertion at the call... https://codesandbox.io/s/zustand-create-initializer-with-storemutator-problem-solution-1-xw11yh?file=/src/App.tsx
- Make `getTestCacheInitializer` use generic `M` and make an type assertion in it's implementation... https://codesandbox.io/s/zustand-create-initializer-with-storemutator-problem-solution-2-3qkjdk?file=/src/App.tsx

The solution that requires no type assertion doesn't exist today.

**Comment by scatterfish** [comment]
The depth of type system intricacies here is far beyond my knowledge so I can't weigh in on the matter of what should be done about it, but thank you for the workarounds in the meantime!

**Comment by devanshj** [comment]
No problems! And haha yeah I wouldn't expect most people to understand it, it was mostly an explanation for @dai-shi and posterity.

**Comment by dai-shi** [comment]
> So let me know @dai-shi, what you prefer out of these two options...

@devanshj 

When I tried some experiments before v4, I thought it would be nice to freely mutate store (especially `setState`), so option 1 would be taken.
However, reading this thread and the fact that all our middlewares in this repo mutate stores as subtypes, I now think option 2 is better even if it comes with a little lie. middlewares should follow the keep subtype rule.

**Comment by dai-shi** [comment]
> 1. No implicit contraints, store mutators can mutate store anyhow, make all parameters of `StateCreator<unknown, [StoreMutatorIdentifier, unknown][]>` as `UnknownBecauseOfGenericMutators`.
> 
> 2. Implicict contraints, store mutators can only mutate the store in a way it remains a subtype of `StoreApi<unknown>`, make parameters of `StateCreator<unknown, [StoreMutatorIdentifier, unknown][]>` same as `StoreCreator<unknown, []>`.

I'm confused, which PR is option 1 and which is option 2?

**Comment by devanshj** [comment]
> When I tried some experiments before v4, I thought it would be nice to freely mutate store (especially setState), so option 1 would be taken.
However, reading this thread and the fact that all our middlewares in this repo mutate stores as subtypes, I now think option 2 is better even if it comes with a little lie. middlewares should follow the keep subtype rule.

Yeah, I kinda agree. The good part is there are still no restrictions, users can use middlewares that don't preserve the subtype relationship and they'd still seamlessly work, it's just that we're making a little assumption to improve types of `StateCreator` when the mutator is generic.

> I'm confused, which PR is option 1 and which is option 2?

Oops, I made mistakes in the descriptions of the PRs haha. #1371 is option 2 and #1372 is option 1.

**Comment by everdrone** [comment]
Hi, don't know if related but searches redirected me here

Is it possible to wrap a `vanilla` `create<T>()` store inside a default `create<T>()(persist())` using typescript?

I'm trying to access the store from inside and outside react components but the `persist` middleware does not accept a vanilla store

**Comment by dai-shi** [comment]
You can't create a store from a store. Just using the vanilla store with persist would be better.

**Comment by everdrone** [comment]
Trying this pattern to have both vanilla and the react hook

```js
import createVanilla from 'zustand/vanilla'
import create from 'zustand'

const vanillaStore = createVanilla(() => ({ ... }))
const { getState, setState, subscribe, destroy } = store

const useBoundStore = create(vanillaStore)
```
(example taken from the readme)

Ideally this implementation would make the react code DRY

but I can't add `persist` to wrap my `vanillaStore`

**Comment by dai-shi** [comment]
You need to use `persist` for vanilla store.

btw, I'm planning to deprecate `create(vanillaStore)` usage in the future. Because unlike v3, it's easy to do in userland with v4 api.

```js
import createStore from 'zustand/vanilla'
import { useStore } from 'zustand'
import { persist } from 'zustand/middleware'

const store = createStore(persist(() => ({ ... })))
const { getState, setState, subscribe, destroy } = store

const useBoundStore = (selector) => useStore(store, selector)
```

**Comment by everdrone** [comment]
That solves it!
but what about typings in the code you provided?

```ts
export const vanillaStore = createVanilla(
  persist<MyStore>((set, get) => ({
    // ...
  }))
)

export const useBoundStore = selector => useStore(vanillaStore, selector)
//                           ^^^^^^^^ selector has implicit any here
```

**Comment by dai-shi** [comment]
You want create()() for TS:
```ts
export const vanillaStore = createVanilla<MyStore>()(
  persist((set, get) => ({
    // ...
  }))
)

export const useBoundStore = <T>(selector: (state: MyStore) => T) => useStore(vanillaStore, selector)
```
