### ISSUE TITLE
[Tips] Connecting zustand store with React state

### ISSUE THREAD

**Issue by dai-shi** [pmndrs/zustand#190]
@timkindberg asked how we could use React state with zustand store.
While this is not the primary use case of zustand, there might be a special use case.
Related discussion: #151 

So, the idea is to sync React state and zustand store.

```js

const createSyncZustand = (useValue, zustandStore) => {
  return (props) => {
    const [value, setValue] = useValue(props);
    useEffect(() => {
      zustandStore.setState({ value });
    }, [value]);
    useEffect(() => {
      const unsub = zustandStore.subscribe(
        (nextValue) => {
          setValue(nextValue);
        },
        (state) => state.value
      );
      setValue(zustandStore.getState().value);
      return unsub;
    }, [setValue]);
    return null;
  };
};
```

Here's the full example: https://codesandbox.io/s/laughing-varahamihira-zr1n1?file=/src/App.js

**Comment by timkindberg** [comment]
Thank you @dai-shi. This is close to what I'm looking for. I'm not sure I care if the state is synced **back** to react. I think it's ok if its only synced from the hook to zustand.

My main goal was:
- **Zustand but with regular react hooks**, as opposed to the proprietary state object and api. I'd actually [brought this idea up](https://github.com/react-spring/zustand/issues/71#issuecomment-565249121) in Dec.
- Because it's "just hooks" it remains ridiculously composable. So things like recoil have ways to merge multiple "atoms" together. This becomes unnecessary because hooks naturally "merge" and compose.
- I'd want the solution to support any type of hook regardless of what it returns (literal, object, array, etc). 

All of those goals were achieved in my POC found here: https://codesandbox.io/s/stately-3-zp0w5?file=/src/App.js

Here is the code. See how we use zustand with any hook, here is an example with a custom`useName` hook. Beyond that zustand works normally.

App.js
```js
import React, { useState } from "react";
import create from "./zustandWithHooks";
import "./styles.css";

const useName = (initialValue) => {
  const [name, setName] = useState(initialValue);
  return { name, setName };
};

const useNameStore = create(useName, "Tim");

const Name = () => {
  const name = useNameStore((s) => s?.name);
  return <span>{name}</span>;
};

const SetNameButton = () => {
  const setName = useNameStore((s) => s?.setName);
  return (
    <button onClick={() => setName((prev) => prev + "!")}>
      Click Me
    </button>
  );
};

export default function App() {
  return (
    <div className="App">
      <Name />
      <SetNameButton />
    </div>
  );
}
```

And here is the implementation. The secret "hack" is to render a react root into an element in memory and allow the hook to be run there. 

zustandWithHooks.js
```js
import React, { useEffect } from "react";
import ReactDOM from "react-dom";
import "./styles.css";
import zcreate from "zustand";

export default function create(hook, ...args) {
  const useZStore = zcreate(() => ({ value: undefined }));
  const reactRoot = document.createElement("div");
  ReactDOM.render(
    <Store hook={hook} args={args} useZStore={useZStore} />,
    reactRoot
  );
  const useStore = (selector, isEqual) =>
    useZStore((s) => {
      if (typeof selector === "function") return selector(s.value);
      return selector(s.value);
    }, isEqual);
  useStore.getState = () => useZStore.getState().value;
  // useStore.subscribe = ...
  // useStore.destroy = ...
  return useStore;
}

function Store({ hook: useHook, args, useZStore }) {
  const result = useHook(...args);
  useEffect(() => {
    useZStore.setState({ value: result });
  }, [useZStore, result]);
  return null;
}
```

Some potential gotchas of my approach:
- Relies on react-dom
- You can't use `useContext` in your hook passed to zustand, but I think that makes sense since the state is essentially global.
- Any other downsides of my approach?

@dai-shi Thank you for brainstorming with me and spending time figuring out how one might sync zustand with React in the other direction. I still have a preference for my original POC. I **do** love your idea of giving the user a component to insert in the tree though where they want. This would avoid having to render with react-dom into an element in memory! I think this would be an optional feature. By default it would still render into memory.

**Comment by dai-shi** [comment]
You are welcome. If you don't need to sync back, then you just don't need to subscribe and it can accept any value. The remaining difference would be hidden react-dom vs. explicit insert.
