### ISSUE TITLE
Using zustand with localStorage

### ISSUE THREAD

**Issue by hsw107** [pmndrs/zustand#195]
Just wanted to give an example using localStorage, same could be used for sessionStorage.

```
const useStore = create((set) => ({
  collection: getLocalStorage("collection") || [],
  setCollection: (collection) =>
    set((state) => {
      setLocalStorage("collection", collection);
      return { collection };
    })
}));

const getLocalStorage = (key) => JSON.parse(window.localStorage.getItem(key));
const setLocalStorage = (key, value) =>
  window.localStorage.setItem(key, JSON.stringify(value));
```

**Comment by dai-shi** [comment]
👍 Closing as resolved.

**Comment by Peculiar-codes** [comment]
window is not defined

**Comment by Tuscan-blue** [comment]
How to solve `ReferenceError: localStorage is not defined` or `ReferenceError: window is not defined`?

**Comment by dbritto-dev** [comment]
@Tuscan-blue it depends on browser `window` and `localStorage` should be defined but on server there's no `window` or `localStorage` you could check `typeof window !== undefined`

**Comment by Tuscan-blue** [comment]
@dbritto-dev Thank you! Finally, I chose not to initialize with `localstorage` in Zustand, but to initialize the state again in `useEffect`. Starting from Next.js 13, both client-side and server-side components are first rendered on the server. The solution using `useEffect` may cause page flickering due to changes in state values (such as switching themes). Using `dynamic()` to dynamically import client-side components and disable SSR can solve the flickering issue. It can also solve `ReferenceError: localStorage\window is not defined`

Reference: https://nextjs.org/docs/app/building-your-application/optimizing/lazy-loading#skipping-ssr
