### ISSUE TITLE
store.subscribe TS error

### ISSUE THREAD

**Issue by lukejagodzinski** [pmndrs/zustand#208]
Hey, I know that there were two issues with this problem reported some time ago and both were closed as solved but they are not. Here is reproduction and comments explaining what's wrong:

```ts
import create from "zustand";

type Mode = "FIRST" | "SECOND" | "THIRD";

export type State = {
  mode: Mode | null;
  name: string;
};

export const useStore = create<State>(() => ({
  mode: null,
  name: "name"
}));

useStore.subscribe(
  (mode: State["mode"]) => {
    // When I try to provide type manually then
    // the selector function gives me an error
    console.log(mode);
  },
  (state) => state.mode
);

useStore.subscribe(
  (mode) => {
    // The `mode` variable is `unknown` here and
    // I don't get any benefit of type system
    console.log(mode);
  },
  (state) => state.mode
);

useStore.subscribe<State["mode"]>(
  (mode) => {
    // This works but that could be done automatically.
    console.log(mode);
  },
  (state) => state.mode
);
```

Source: https://codesandbox.io/s/sad-shamir-9ezqu?file=/src/index.ts

Any plants to solve this issue?

**Comment by dai-shi** [comment]
There are two issues to note.
1. subscribe with selector returns `null` when error occurs. So, `null` is special here, which conflicts with `Mode` in your case.
2. With context sensitive function, TS can't infer types.

The first one is only problem when slice value has `null`. See this example without `null`: https://codesandbox.io/s/friendly-curie-txfx1
We might be able to come up with better one for this, but I'm not sure. (at least without breaking change, it wouldn't be possible.)

The second one is not solvable by us. It's TS's behavior. Luckily, you found a solution! I didn't know you can attach slice type in `subscribe`.

**Comment by lukejagodzinski** [comment]
@dai-shi oh I didn't know that `null` is a special case. There is no mention of that in docs. In theory I could use `undefined` but that's kinda hacky to deal with the library problem in that way. I should be able to use whatever type I want in the state.

Also providing error as the second argument is kinda breaking the well established callback structure which always was like:
```ts
(error, result) => {}
```
I guess, it could provide error info in some other way or just don't pass it at all. In the code, I can see that it's only being used when selector or equality function fails: https://github.com/pmndrs/zustand/blob/f32aa02d16f001e659131b9f1f2a27f3680d383d/src/vanilla.ts#L64
I feel like if someone has error in this part of the code then this app shouldn't work in the first place and error could be thrown into the global context as well. It's not like catching error because of application logic.

For the second problem, yep I guess it's not actually possible. I've tried quickly coming up with some solution but I'm not advanced enough with TS to do it. But maybe it's just not possible yet. Other solution could be just passing entire state there and not just slice. It's a little bit counter intuitive to pass slice there. The selector should tell when the listener function should be rerun but I would like to always rerun it with the entire state. But that would be a breaking change.

Also API could be different. For example:

```ts
store.subscribe((state) => state.mode)((stateSlice) => { // Do something with the slice });
```

So the `subscribe` function instead of collecting listener would return "subscribers" collection for a particular selector and then we could attach listener by calling `subscriber(listener)`. In such a case inferring types is easy.

**Comment by dai-shi** [comment]
> I should be able to use whatever type I want in the state.

I don't disagree.

> `(error, result) => {}`

This will break the current behavior. https://github.com/pmndrs/zustand#readingwriting-state-and-reacting-to-changes-outside-of-components
It's not worth a breaking change. This would be major version up.
Same for `store.subscribe((state) => state.mode)((stateSlice) => { // Do something with the slice });`

> or just don't pass it at all.

This might be possible. It's technically a breaking change, but it's undocumented, so maybe we can avoid major version up.

> I feel like if someone has error in this part of the code then this app shouldn't work in the first place and error could be thrown into the global context as well. It's not like catching error because of application logic.

If this is the consensus, we can remove try-catch and `StateSliceListener` type will be simplified.
What do others think? cc @drcmda @JeremyRH 

@lukejagodzinski Would you like to draft a PR for discussion? (note we are still not sure if it's accepted or not.)

**Comment by dai-shi** [comment]
(Nobody responds...

**Comment by drcmda** [comment]
copying this bit from discord:

we constantly bumped into this before. it only got better after implementing it after redux decided to do so as well for the same reason
redux uses a similar pattern, they store it as latestError https://github.com/reduxjs/react-redux/blob/master/src/hooks/useSelector.js#L30-L46
GitHub
reduxjs/react-redux
Official React bindings for Redux. Contribute to reduxjs/react-redux development by creating an account on GitHub.

With hooks, there is no way to render a context provider, which means there's also no nested hierarchy of subscriptions. Because of this, the "stale props" and "zombie child" issues may potentially re-occur in an app that relies on using hooks instead of connect().
useSelector() tries to deal with this by catching all errors that are thrown when the selector is executed due to a store update (but not when it is executed during rendering). When an error occurs, the component will be forced to render, at which point the selector is executed again. This works as long as the selector is a pure function and you do not depend on the selector throwing errors.
im kinda afraid of this coming up again, because it made such a mess in the first months of running zustand in the wild, made us scratch our heads, because the error messages made no sense at all
and even if they made sense, there was nothing that we could do other than padding out all selectors system wide with undefined checks which added hundreds of LOC
@daishi do you think with all the latest changes these problems are gone?

**Comment by dai-shi** [comment]
@drcmda 
I am familiar with the stale props issue. This change won't affect it, simply because it's not used by the useStore hook.
The point here is it's only about the vanilla api, which is not used by the react hooks api. (we can use it as `useStore.subscribe(listener, selector)`.
