### ISSUE TITLE
New to Zustand: State Selection and Optimization

### ISSUE THREAD

**Issue by mbrahimi02** [pmndrs/zustand#218]
Hello, I recently decided to check out Zustand after hearing a few developers in the community talk about it, however, I'm failing to understand what benefit it has over the context API. In fact, it seems to have some of the same issues.

https://codesandbox.io/s/lingering-cdn-yqo4b

In this example, I have a store with two keys count and other, as well as an inc function to increment the count value of the store. There are 3 components which destructure each of these from the store, but you'll notice that when I hit the increment button all 3 components rerender. This is analogous to the context API in which useContext subscribes to changes in the entire value instead of a single key. So where exactly is the benefit here?

**Comment by bhgsbatista** [comment]
I think this is mostly useful if you want to connect two separate react components together, as far as what the difference is with the context API, there doesn't seem to be any other than this is more easy to test since you don't need to inject some provider at the root of your React tree.

For more efficient state tracking / rendering logic look towards MobX as it listens for property access through proxies and only updates your component if that specific property changes.

**Comment by JeremyRH** [comment]
Use a "selector" function to subscribe to part of the store:
```js
const count = useStore((store) => store.count);
```
This will avoid a re-render if other properties on the store change.

**Comment by bhgsbatista** [comment]
I am impressed.

**Comment by dai-shi** [comment]
Closing as resolved.
