### ISSUE TITLE
v3.3.3 broke some TS types 

### ISSUE THREAD

**Issue by Akuukis** [pmndrs/zustand#393]
## Summary

v3.3.3 introduces a breaking change for Typescript users that use `set` with callback with multiple return statements. See repro.

Please advice how to type this properly after v3.3.3.

## Workaround

I don't know.

## Minimal Repro

```ts
import create from "zustand/vanilla";
import { combine } from "zustand/middleware";

const TestStore = create(combine({
    locked: false,
    amount: 0
  }, (set) => ({
    setAmount: (newAmount: number) => {
      // Works until 3.3.2, TS-errors on 3.3.3 and later (up to current 3.5.1). Note multiple returns.
      set(({ locked }) => {
        //^^^^^^^^^^^^^^^^^
        // Argument of type '({ locked }: { locked: boolean; amount: number; }) => { amount?: undefined; } | { amount: number; }' is not assignable to parameter of type 'PartialState<{ locked: boolean; amount: number; }, "amount">'.
        // Type '({ locked }: { locked: boolean; amount: number; }) => { amount?: undefined; } | { amount: number; }' is not assignable to type '(state: { locked: boolean; amount: number; }) => { locked: boolean; amount: number; } | Pick<{ locked: boolean; amount: number; }, "amount">'.
        //   Type '{ amount?: undefined; } | { amount: number; }' is not assignable to type '{ locked: boolean; amount: number; } | Pick<{ locked: boolean; amount: number; }, "amount">'.
        //     Type '{ amount?: undefined; }' is not assignable to type '{ locked: boolean; amount: number; } | Pick<{ locked: boolean; amount: number; }, "amount">'.
        //       Type '{ amount?: undefined; }' is not assignable to type 'Pick<{ locked: boolean; amount: number; }, "amount">'.
        //         Types of property 'amount' are incompatible.
        //           Type 'undefined' is not assignable to type 'number'.ts(2345)
        if (locked) return {};
        
        return {
          amount: newAmount
        };
      });
    },
    setAmountForced: (newAmount: number) => {
      // Works always. Note single return.
      set(({ locked }) => {
        return {
          amount: newAmount
        };
      });
    }
  })
));
```

**Comment by dai-shi** [comment]
Okay, this is something we didn't realize when working on #320. (So, missing tests for types.)

First off, if I understand correctly, you want to bail out if `locked`.
In such case, you should return a previous state, not `{}`.

Then, I made this work.
https://codesandbox.io/s/serverless-hill-zdm1h?file=/src/App.tsx
It's still tricky, but it seems TS can't infer types.

Returning `{}` can't be typed unfortunately.

---
This reveals that we can't return arbitrary partial state. (JS works but TS doesn't)
 ```ts
  set((prev) => {
    if (prev.a) {
      return { b: 1 }
    }
    return { c: 2 }
  })
```
This can't be typed. Any thoughts? @TkDodo

**Comment by TkDodo** [comment]
hmm, I have reproduced this in a simple counter example:

https://codesandbox.io/s/romantic-moon-xxkzd?file=/src/App.tsx

the error is quite expressive:

```
Argument of type '(state: CounterState) => CounterState | { count: number; }' is not assignable to parameter of type 'PartialState<CounterState, "count" | "foo" | "inc" | "dec">'.
```

oddly enough, returning a new object makes it work:

```diff
  inc: () =>
    set((state) => {
      if (state.count === 5) {
-        return state;
+        return { ...state };
      }
      return { count: state.count + 1 };
    }),
```

let me check if we can include the full state type in the return type of the `set` function

> This reveals that we can't return arbitrary partial state.

I don't understand that because the example is doing exactly that:

```
dec: () => set((state) => ({ count: state.count - 1 }))
```

can you elaborate a bit?

**Comment by dai-shi** [comment]
> > This reveals that we can't return arbitrary partial state. (JS works but TS doesn't)
> > 
> > ```ts
> >  set((prev) => {
> >    if (prev.a) {
> >      return { b: 1 }
> >    }
> >    return { c: 2 }
> >  })
> > ```

> can you elaborate a bit?

Sorry, I jumped away from the OP example. The point is it returns a union of partial state.

```ts
type State = {
  a: boolean
  b: number
  c: number
}

type SetState = (prev: State) => Pick<State, 'b'> | Pick<State, 'c'>
```
Something like this.

**Comment by TkDodo** [comment]
okay, I see. I need to think about it a bit :)

**Comment by dai-shi** [comment]
@Akuukis 
Returning `{}` will create a new state object and trigger re-render. (The bail-out behavior isn't written anywhere in docs. I wonder even if React docs have it.)
Have you checked my codesandbox link?

**Comment by TheEhsanSarshar** [comment]
**off-topic:** 
have you noticed? how machine-friendly is the typescript errors

**Comment by TkDodo** [comment]
@dai-shi I've based the typings on `setState` of class-based react components, and it turns out: they heave the same issue 😮 

have a look here: https://codesandbox.io/s/cool-shadow-7skmt?file=/src/App.tsx

Not an excuse, but I really don't know how to effectively fix it, and there are some workarounds like spreading the previous state into the return object.

**Comment by dai-shi** [comment]
> @dai-shi I've based the typings on `setState` of class-based react components, and it turns out: they heave the same issue 😮
> 
> have a look here: https://codesandbox.io/s/cool-shadow-7skmt?file=/src/App.tsx

Well, zustand has a different requirement (`PartialState`) from React's setState.

> Not an excuse, but I really don't know how to effectively fix it, and there are some workarounds like spreading the previous state into the return object.

"spreading the previous state" workaround is worse than "as any" workaround, IMO, because it's not type only (technically an overhead in JS).

---
I played a bit and came up with this. Not pretty at all, but seems to work. 👉  [playground](https://www.typescriptlang.org/play?ssl=51&ssc=15&pln=51&pc=29#code/KYDwDg9gTgLgBDAnmYcDKMCGNUF44QBGAVsAMYwBQA9NQssAM5wCWAdo2C1MACZyFEcRsBgZsqAGZQIAWzgAlYJgoAaYcGAAuGnQAWMGGEZbaAcxYw9AV0IA6MnOoARYJPaXgAG0QAVBrwubh44Pv4ogYReRNQAbGQALACcwAkArAAcCQBMAMyZhJhpSUUADBnAAIy51aUA7EmVSRlJjZUJuaWBSCiM1DwqMNQAbpWx1Oy8oHa8djCMAMQAMgktALQrSWmUoJCw9ChwAAqYsCyYXuI4ADy+cKA4bLzMV8DqANL3II-PcADWwEQEEkcF8AD44LhKHA4AAfOAACiOLDIf1uHwh8N8AEpoXDEQjGFgcFpQdjIRDkaj0XB3piyTtwNB4D1UCczhdXtlbl8fi9iW9aZVecAnswAUCQb4PtkRWL-oDgaCIVCYfCkSi0dKhfSqVqZfScXj1YSBaScRTjpqae9Krrrdr3tlDbjdsyDmzTjBzpcBbkeQ9Rb9Xh9hYH5RKlY7ZeHfpGpR9cnK44qpSrjYi9Ta7fis9H7dTHbkXRmEaaJObybhKQ7QwX9bTnbna7Ti-ijW79qzjl6fa8EgHvkH+RJQ8nxanQTLxwrJVPWzP4-P3glF5PwZDS3m683Cwbdw33m34dvaQkS2qCUSK2TLafbfWbU2Ty2j4-Hef266mV2GOgBWg3jkDA0CDny-6jnAACqKqIteJK3tW0GMnsLJ-gAogAjtYFyWIgADCejkACUC3LB5YIdqbDAAA7q8laWoQEAQF4yhsCh7rdq8SwsESorAKRG74BR2jzmAPDDCwEDWIw9GIRCwwQCwvAcb+hyvGgXgosAPF8dRgnkYwWlkKJ2ricAknSbJxmmVWClKSpnbwOwOBQJIKioGgtiMGQUAsIQwBgcOEE4BCADeeIIlpekCaS3G8Y8AlkdipIInZcCKcpeLXBpNlggieIwtFiVQHFAE2bpJU5eV2lgqohUaKxFDQAA-GVEiAU1IGCeouW1fVMIwsA2G4UgABibBtXAWE4VpSCEcRSV9SZYJ4iliLpZlKkAL6UKpaHqaIrxBfKrywRFMLXLaa5ztGN1Rom90JmeT3KgiYC9hcpLst6nICgOjqVDKiYfOe6g8GAXgeVNTEsWx61bdl12xhOt3Tijs4PQuGNLuC72fV430E68-qA8DrZ1XAENQyZMPMaxmBsAjDlI2GQ4Ruu6Psymt35R9HKEz2AtctmBrg8AkPQ6SsMM0zpKI5dnw4+ufME0TwsCjalPU1LAj0-D8ss7tTkenAADiR2a3cGNnZCG2Wr4+2m64RIyEIwmbSzJsuQJ7kmf+0DAAAglwJ3BgK4V4iIYhmuglsSGReJmPHCEWzHCfglH3m+f5oleYQPl+QFicwlMrsQIgpIuzAbuUMbP4HZ5Ar4QM3VhyOODqPhMkgbIgHpzgdv98d4LkVHoikt3RJyMPAoDXAycwKSacj3VeKYFwZWByHLCJ+ljt7Y4HDwNPPB2wARLw1iyLIiDn3AmDMNYbB-GwEA0WwD-8tvodhXAkjMVJK7dgZgADcAhTikjYNfAKUA4DbVWqfYAdho7HXPgAiA591Dn0KFAc++U0qWguqwEECIACy2A9B2CgIzXgchCEQlKHYNI5JiEwh4DAawUBP5-wwaSdBzF77bVAXiXa7DRBcJ4RA0qcBhTCLrtiERlAgA)

Any idea to improve it?

**Comment by TkDodo** [comment]
you would apparently still need to manually annotate the generics, but it's a workaround that's hopefully good enough.

the solution of explicitly specifying generics also means that we can `return previousState` 👍

**Comment by dai-shi** [comment]
`return previousState` is possible as of now, I guess.

**Comment by TkDodo** [comment]
> So, return previousState will work if we explicitly annotate it. (for other picked keys)

yes, it looks like it needs the generic to be passed. strangely, type inference seems to work when doing `{ ...previousState }` instead.

@dai-shi I think your solution is good enough. Sure, it only allows for 4 keys, but then again, you only need it if different branches return different Picks of keys.

I wasn't able to come up with anything better. Do you want me to PR it, or are you doing it yourself given it's your idea?
Only other option would be to revert #320, which would make typings more loose and would easily introduce bugs / not show type errors if you refactor from an optional prop on your state to a required prop...

**Comment by dai-shi** [comment]
@TkDodo Sounds fair.

> Do you want me to PR it, or are you doing it yourself given it's your idea?

It's helpful if you can work on it. Please go ahead.

**Comment by TkDodo** [comment]
I found a condensed version that uses default parameters for the generics, what do you think?

[playground](https://www.typescriptlang.org/play?ts=4.2.3#code/KYDwDg9gTgLgBDAnmYcDKMCGNUF44QBGAVsAMYwBQA9NQssAM5wCWAdo2C1MACZyFEcRsBgZsqAGZQIAWzgAlYJgoAaYcGAAuGnQAWMGGEZbaAcxYw9AV0IA6MnOoARYJPaXgAG0QAVBrwubh44Pv4ogYReRNQAbGQALACcwAkArAAcCQBMAMyZhJhpSUUADBnAAIy51aUA7EmVSRlJjZUJuaWBSCiM1DwqMNQAbpWx1Oy8oHa8djCMAMQAMgktALQrSWmUoJCw9ChwAAqYsCyYXuI4ADy+cKA4bLzMV8DqANKV9yCPz3AA1sBEBBJHA7vhAcDQb4Ptlvr9mJCQWC4PhPh9cvDgE9EUDkeC4O9sh8ElicQC8dDUYTcgA+VGUOBwAA+cAAFEcWGR-rcPpV6azOdzeYTsgLjlyeTCaeKhVKSeLfABKRks9lsxhYHBaMFK1H0uUiz6yyVGsVqw3S950i2mq0JRUq3bQeA9VCvNDecgwaC3Ml-V7qACq9PwGq12l1+rgQZ24BdB1QAFEAI7WC6WRAAYT05EBUFuofZmokOulbGAAHdXmW9bh6YQIBAvMo2HG9q6GOgI0sWJrscAC74i+HS2D1GAeMMWBBrIwa1H63BhhAWLx2wm3d2JGgvFzgL3+xWhyPGHuyJHpZPgNPZ-Pz5e6-SV2uN-t2DgoJIVO7bIwyFALCEMAfoPNiAYRvSADeqpsnuR6DjqryHo8g6FkqOpsk+y6ruuTLXB6D60myqpMvBqFQEhEa7vuKEDgWhH7rSqikRoLYUNAAD8VE7l6HFDuojEXsxrHAGmGZIAAYmw3FwKm6Z7kgOZ5mhQnALSqoYey2EvuuAC+lBvp2hyemIEagT84EvJB1Iwfhnz+riUIohClLjqKjkUs5BLojSnlIlSaLEoSpJgeSAUuTKbJgKcMDnF4OonGcFyvEalSwhiCrqDwYBeD+smNs2rZabplAGc6+xbgA4qIqV3GFEESCO2G+EZiZwK4moyEIYY6bhbUfoO34Xt20DAAAglwFkItuODQaqIhmWOpl1RpTJmLVEY6jVS03MOC1-gBQGRmgh2AcBhaqlMXUQIgOqdTA3VlW1W6vFmAw+kOnmBnAWZzj6sgrRG1JAxIhYjgtog6n9mpyKDOAsetUNwDtq2I3AmBcFRY2TSwl0tYZlCOBw8Cwzw1IAES8NYsiyIgFMY8w1hsP8bAQJWbCM6NPC49cUFwJITY6l17BmAA3AIpw6mwNPAVAcB6RpZPAHYi2pQA5ILEDq+o6uFFA6vEVh0Z2awoJsgAstgeh2FAmBPHIxv0qUdhpHqptMjwMDWFAnP81rOoU1rDN6WLqoGZ7og+37kuUXAXyh2VSph5QQA)

for some reason, both approaches work in the sandbox but not in zustand. I mean it works but I noticed some issues when writing tests. I'll open a draft PR and we can discuss there

**Comment by dai-shi** [comment]
@Akuukis Would you like to confirm if #397 fixes your use case? You can try with the codesandbox build.
