### ISSUE TITLE
How to dispatch actions in Components

### ISSUE THREAD

**Issue by nayyaung9** [pmndrs/zustand#485]
As I am learning zustand, I really like it. It is simple, lightweight and super fast.
So I am trying a new project and I have a question.

How can i fetch actions via UI?

This is my orderStore file
```
const orderState = create((set, get) => ({
  orders: [],
  getOrders: async (orders) => {
    try {
      set({ orders });
      return get().orders;
    } catch (error) {
      throw error?.response.data || "An Error Occured";
    }
  },
}));

export default orderState;
```
And I want to call this action in Component ( .tsx )
How can i do that?
If I call within useEffect it say Hooks Error.

```
const getOrders = orderState((state) => state.getOrders);
```
Please Help Me.

**Comment by dai-shi** [comment]
yes.

The idiomatic way is to get a callback with useStore.

```js
const useOrderStore = create((set) => ({
  orders: [],
  getOrders: async () => {
    try {
      const orders = await fetchOrders();
      set({ orders });
      return orders;
    } catch (error) {
      throw error?.response.data || "An Error Occured";
    }
  },
}));

const Component = () => {
  const getOrders = useOrderStore(state => state.getOrders);
  useEffect(() => {
    getOrders().then(orders => console.log(orders));
  }, [getOrders])
  // ...
}
```

**Comment by meglio** [comment]
@dai-shi , will this only work for one-level selectors only?

`const getOrders = useOrderStore(state => state.getOrders);`

Will it notice changes to deeply nested properties like in:

`const getOrders = useOrderStore(state => state.MYOBJECT.getOrders);`

**Comment by dai-shi** [comment]
It works even if it's nested. The caveat is that you need to merge when updating the state. The library only shallow merges it.

https://github.com/pmndrs/zustand/blob/896554237eb1c258bc20e0c87abe9eba65282a66/src/vanilla.ts#L68

**Comment by dai-shi** [comment]
Closing as answered.

**Comment by jrhager84** [comment]
How do you return the error object though? It doesn't seem efficient to manage a HUGE list of error objects in the store for consumption from components (form errors for instance). How do you return an error in a catch in the store?

**Comment by dai-shi** [comment]
As actions in store are just functions, you can throw and catch errors. Or, do you mean how error objects can be stored in useStore?

**Comment by jrhager84** [comment]
I think I figured it out, but I wanted to just reiterate to cement it in my mind:

I have a try/catch in my component that just calls the function, and I handle the errors there, right? I shouldn't need a try/catch in the store because whatever comes back will be handled by my try/catch in my component. Is that the intended architecture?

**Comment by dai-shi** [comment]
It depends. If the error is something that should be handled in a component, do so. Otherwise, I would probably catch the error in store actions and change store state. I'm not sure if I understand your case. Maybe open [a new discussion](https://github.com/pmndrs/zustand/discussions/new) with some code snippets?
