### ISSUE TITLE
`persist` middleware `Content Mismatch` error with Next.js

### ISSUE THREAD

**Issue by ExpressGradient** [pmndrs/zustand#510]
Since Next.js does SSR, I'm facing a content mismatch error while using the `persist` middleware.

**Comment by AnatoleLucet** [comment]
Hey, could you give a bit more information on the issue you're facing? A codesandbox would be great 🙂

**Comment by ExpressGradient** [comment]
Hey, so what happens is, Next.js tries to prerender the requested page.
So, if you use the persist middleware, the state is persisted in the local storage.
But, there is no local storage at server side, it tries to render with default state and serve.
But after the page has been served, client side hydration happens and this time since local storage is present, it renders with local storage state. Next.js compares this server rendered content and client rendered content and throws a `Content Mismatch` error.

Here's the relevant code,
https://github.com/ExpressGradient/next-bank/blob/19519df970cadc0e3d284192f43e6e7f142bc28a/stores.ts#L9
https://github.com/ExpressGradient/next-bank/blob/19519df970cadc0e3d284192f43e6e7f142bc28a/pages/register.tsx#L152


Correct me, if I'm wrong

**Comment by AnatoleLucet** [comment]
Basically, `localStorage` is not available on nextjs' server because it's a Web API (and Web APIs are not available in nodejs), so the `persist` middleware is unable to retrieve any persisted data (hence why the store returns the default state).

You can probably fix this in a fiew ways:
You could have some kind of storage available on both the server and the client (with synced data). But I really don't know if a ready to use solution exists, or even it would be viable.

Another (though not so clean) solution, would be to render your components only after React's hydration (aka at the 2nd render) with - for example - a custom hook:
```ts
function useHasMounted() {
    const [hasMounted, setHasMounted] = useState(false)

    useEffect(() =>{
      setHasMounted(true)
    }, [])

    return hasMounted
}

function FormSwitch(): JSX.Element {ExpressGradient, 3 days ago: • added OTP form, Form Message
    const show = useRegisterState((state) => state.show);
    const hasMounted = useHasMounted()

    if (!hasMounted) return "Loading..."

    switch (show) {
        case "REGISTER":
            return <RegisterForm />;
        case "OTP":
            return <OTPForm />;
        default:
            return <RegisterForm />;
    }
}
```
The main issue here, is that `"Loading..."` might flicker since it's instantly overridden at the 2nd render.

The last solution (and probably the cleanest) I have in mind, is to use [Nextjs' authentication](https://nextjs.org/docs/authentication) to get the information you need on the server.

**Comment by ExpressGradient** [comment]
Hmm, I solved my issue by storing the state in redis. I think it might be cleaner, but more expensive.

**Comment by api42** [comment]
I solved by saving the state in react hooks and using useEffects.

**Comment by PhilipWee** [comment]
The below worked for me, probably similar to what api42 did

```
const [data, setData] = useState<Data | undefined>();

  useEffect(() => {
    setData(useStore.getState());

    useStore.subscribe((newData) => {
      setData(newData);
    });
  });
```

**Comment by osaxon** [comment]
Old thread but I'm having the same issue and having to implement useState and useEffect as mentioned by PhilipWee and api42.
It doesn't feel like a good solution though to me as I'm having to write states twice in my components - one to store the Zustand state value from localStorage and then one for my useState. Feels a bit hacky.

**Comment by moiezshaikh18** [comment]
> Hmm, I solved my issue by storing the state in redis. I think it might be cleaner, but more expensive.

Can you please tell how you store your data in rediscache
