### ISSUE TITLE
Which one has a better performance? redux or zustand

### ISSUE THREAD

**Issue by khongten1452** [pmndrs/zustand#530]
I'm a beginner, and I'm trying to make a game on react. I used redux in my project and did not really care about which one was simpler to use, but now I want to know which one is the right tool for game development? 
Redux is the fastest tool in the web, but is it the right tool for react game? I did read the brief comparison here https://github.com/pmndrs/zustand#why-zustand-over-redux
I read some where that using redux programming pattern, one can sperate view and and logic, which can be put in separate threads for better performance. I really want a more thorough comparison and maybe some benchmarking. Thanks!

**Comment by drcmda** [comment]
zustand is used in multiple games, for instance https://github.com/pmndrs/racing-game or https://twitter.com/0xca0a/status/1184586883520761856 and these have state that updates 60fps which is something that zustand probably handles better because it has selective subscribe. zustand will also work better with your reconciler, for instance react-three-fiber, because it doesn't use context, which is a drawback. i don't think there's a difference botherwise etween the two for just update overhead.
