### ISSUE TITLE
Can't auto generate selectors when using Context?

### ISSUE THREAD

**Issue by samuelcolburn** [pmndrs/zustand#549]
Apologies if this is already common knowledge, but I was trying to move some of my stores over to `createContext`, and the patterns that I've used previously from [Auto Generating Selectors](https://github.com/pmndrs/zustand/wiki/Auto-Generating-Selectors) don't seem to work when using `createContext`.

It looks as though once the store is created, it can't be manipulated, so adding keys to the store after it's already been created doesn't do anything. I suppose this makes sense, but that leaves me with some semi-painful refactoring to do going around replacing all of those references in various components. 

If that's the case, is there a different way to go about it that will achieve a similar result? Even if I have to update a bunch of components, losing the pattern entirely would be a bummer as it's quite convenient.

Sandbox link:
https://codesandbox.io/s/optimistic-ganguly-35ryy?file=/src/store.js

**Comment by dai-shi** [comment]
`zustand/context` is provided to misuse zustand with context, which may violate rules of hooks, and it only supports `useStore` pattern.
It's unfortunate for you that it doesn't allow custom attached hooks.
You have two options:
1) create your version of `createContext` and attach custom hooks in it.
2) keep using the current store and simply pass it through context and be careful not to replace the store at runtime.

I guess option 2 would be just good for you.

**Comment by lubieowoce** [comment]
> `zustand/context` is provided to misuse zustand with context

@dai-shi hi! i started playing around with making the `context` a bit less hacky (i.e. more in line with the letter of the hook rules), is that something you'd be interested in getting a PR for? i understand `context` isn't the main focus, so i thought i'd ask first :)

(it looks like it'd require breaking changes to both `createContext` and `Provider`[1], so now seems like a good time to ask, given that `4.0.0` is on the horizon)

---

[1] basically, it'd require passing the `createStore` function to `createContext` rather than to the `Provider`, and refactoring `zustand.create` a bit

**Comment by dai-shi** [comment]
@lubieowoce Hmmm, I can't tell... If you have a really new idea, it might be worth. To my knowledge, it's hacky because `create` returns a hook. If we have a separate `useStore` hook exported, we don't even need `zustand/context`. I would like to explore that path, which was not possible with uMS, but with uSES, it should be possible.

**Comment by lubieowoce** [comment]
I'd love to talk about this more (if you've got the time) but i don't want to derail this issue further, should I open a thread in Discussions instead?

**Comment by dai-shi** [comment]
That would be a good idea.

**Comment by dai-shi** [comment]
Closing this as answered. Also, this might be improved in the future version.
