### ISSUE TITLE
Different behaviour of LocalStorage and AsyncStorage

### ISSUE THREAD

**Issue by steida** [pmndrs/zustand#583]
In my app, I'm using @react-native-async-storage/async-storage because I plan to support React Native.
But because React Native is not expected to be supported soon, I decided to switch back to LocalStorage
and my app stopped working. If I will add setTimeout to `state.dispatchStoreRehydrated();`, it works.
It's probably because LocalStorage is sync while AsyncStorage isn't.

```ts
onRehydrateStorage: () => (state) => {
  if (state)
    // Fix for LocalStorage. With AsyncStorage, setTimeout
    // is not required.
    setTimeout(() => {
      state.dispatchStoreRehydrated();
    }, 0);
},
```

**Comment by AnatoleLucet** [comment]
Not sure what you mean by "my app stopped working". Can you send enough code to reproduce (the full code of your zustand store, a component that doesn't work as expected, etc.)?

Though, there's indeed a difference between a sync and an async storage. With a sync storage, your zustand store will be hydrated at the initial render. With an async storage, your zustand store will be hydrated asynchronously (a.k.a. at some point after the initial render).

**Comment by AnatoleLucet** [comment]
> I think such inconsistent API is confusing. Zustand should not fight with async storage API but embrace it. All storages are async, Sync LocalStorage is a very rare exception and definitely not recommended because it's blocking the main thread. Propagating that storage has been hydrated is not a hack but a useful piece of information.
> 
> I can help you to redesign it for version 4 if you want.

I mean, if you can answer: how can sync storage users not pay to cost of async storages & consistency (which they don't use... because... sync), then sure, let's do it.

**Comment by steida** [comment]
> I mean, if you can answer: how can sync storage users not pay to cost of async storages & consistency (which they don't use... because... sync), then sure, let's do it.

Which costs exactly? They can use it as they are already using it. The only problem I can imagine is saving something then unloading tab immediately without waiting for success. Or did you mean something else?

**Comment by AnatoleLucet** [comment]
That's not fixing the hack, that's just embedding it.
Sync users still pay the cost of not having the data at the initial render. And yes, that's *almost* solved by React batching renders (though I'm not sure if they batch the initial render since it might increase TTI :thinking:).
But what if you have 2 or more individual stores using this middleware. Then you'd need to programmatically wait for each of them? I mean, that's still increasing the cost of consistency...

**Comment by AnatoleLucet** [comment]
> As for more stores, I have to admit I don't understand why it should be useful, it's for separate bundles?

I personally like to create a bunch of stores, each with its own context. A bit like redux reducers for instance.

**Comment by steida** [comment]
As I see it, the current persist implementation should be reimplemented.

1) LocalStorage can't stay sync because of all other async storages.
2) Because persist is async, it has to expose isPending and some callback for persist completed.

That would cover all my and other people use-cases I suppose. 
Can I help you with that somehow?

**Comment by AnatoleLucet** [comment]
I might have misunderstood. I was just thinking of adding an option to toggle between smart and dump mode.

**Comment by steida** [comment]
Can you explain to me why smart/sync mode is required, please?
As I see it, it only complicates SSR and I don't see any benefit of it.

**Comment by steida** [comment]
Sorry for reopening, but it probably belongs here anyway.

I believe both use-cases (sync and async) are valid, but common API for that does not make sense.

What I am suggesting is to split implementation to syncPersist (LocalStorage or SessionStorage or even cookie) and asyncPersist (for everything else).

It would simplify implementation and make it explicit as well.

What do you think?

**Comment by AnatoleLucet** [comment]
Since the middleware now have an [api](https://github.com/pmndrs/zustand/wiki/Persisting-the-store's-data#api) that can easily be used to check for hydration, [some docs about async hydration](https://github.com/pmndrs/zustand/wiki/Persisting-the-store's-data#hydration-and-asynchronous-storages), and [a few examples to demonstrate how to reactively check hydration status](https://github.com/pmndrs/zustand/wiki/Persisting-the-store's-data#how-can-i-check-if-my-store-has-been-hydrated), I believe this issue can be closed.
@steida Feel free to give any feedback.

> Maybe it's problem on my side and I should create my own persist

I guess you could create your own wrapper middleware around `persist` to promisify the storage.
Something like this maybe ?
```ts
export const asyncPersist = (config, options) => {
  const { setItem, getItem, removeItem } = options.storage;

  options.storage = {
    setItem: async (...args) => setItem(...args),
    getItem: async (..args) => getItem(...args),
    removeItem: async (...args) => removeItem(...args),
  };

  return persist(config, options);
};


const useStore = create(asyncPersist(
  (set, get) => ({
    ...
  }),
  {
    ...
  }
))
```

**Comment by steida** [comment]
LGTM

**Comment by a-toms** [comment]
This is not working currently. See https://github.com/pmndrs/zustand/issues/1145 for a fix as of writing.
