### ISSUE TITLE
Typescript issues with set function when creating store

### ISSUE THREAD

**Issue by ghtaylor** [pmndrs/zustand#656]
I'm using the basic example to create a store from the documentation and I'm getting the Typescript issues as seen in the screenshot below. These include `object is of type 'unknown'.` and `Parameter 'state' implicitly has an 'any' type.`. Can somebody please assist?

Zustand version: 3.6.5
Typescript version: 4.4.4

![image](https://user-images.githubusercontent.com/5741857/141482033-835ef794-aab3-474a-b7c0-b8717ca21b47.png)

![image](https://user-images.githubusercontent.com/5741857/141482093-54d871f9-cb34-4968-afbb-efb3fb964271.png)

**Comment by ghtaylor** [comment]
Had to provide type parameter to create function.

**Comment by dai-shi** [comment]
Yeah. FYI, if you want the types to be inferred, the `combine` middleware might help.

**Comment by juanchoperezj** [comment]
I faced a similar issue because I forget to add the proper types to one of the functions on `BearState`, e.g:

```
import create from 'zustand'

type BearsState = {
  ...
  createBear: (bear: BearState) => void
}
```

**Comment by abdulkarimyulchibekov** [comment]
If there is a persist from middleware for save our store to localstorage it doesn't works

**Comment by Favourz1** [comment]
The errors you're seeing can be resolved by typing your store state and actions. Here's how to fix the example:

`import { create } from "zustand";

interface BearState {
bears: number;
increasePopulation: () => void;
removeAllBears: () => void;
}

const useStore = create<BearState>((set) => ({
bears: 0,
increasePopulation: () => set((state) => ({ bears: state.bears + 1 })),
removeAllBears: () => set({ bears: 0 }),
}));
export default useStore;`


The key changes to note:
1. Define an interface for your store state and actions (`BearState`)
2. Use the generic type parameter with `create<BearState>`
3. TypeScript will now properly infer the types for `state` and ensure type safety

These errors occur because the compiler needs to know the shape of your store's state and actions. By providing the interface, you give TypeScript the information it needs to properly type-check your code.

If you're using TypeScript 4.4.4 with Zustand 3.6.5, this solution should work perfectly. 
Let me know if this works for you!

**Comment by davidvalen95** [comment]
extending @yarapolana answer
To avoid duplication and redundancy, we can utilize `type utilities`

```
const BearConfig = (set) => ({
  bears: 0,
  increasePopulation: () => set((state) => ({ bears: state.bears + 1 })),
  removeAllBears: () => set({ bears: 0 }),
});

export const useBearStore = create<ReturnType<typeof BearConfig>>(BearConfig);
```
