### ISSUE TITLE
[middleware/persist] compatible issue, does't work on iOS 9

### ISSUE THREAD

**Issue by lili21** [pmndrs/zustand#677]
Error Message
`DOMException: The quota has been exceeded`

**Comment by lili21** [comment]
I'm using default storage, which is localStorage

**Comment by AnatoleLucet** [comment]
That's pretty low on clues 😄
Are you using React Native? If so, `window.localStorage` won't be available because it's a web api. You might want to use something like [`AsyncStorage`](https://github.com/react-native-async-storage/async-storage).

If you're not using React Native, or it still doesn't work with AsyncStorage, could you send enough code to reproduce the error?

**Comment by AnatoleLucet** [comment]
By what I'm seeing, you might also be using too much space in `localStorage`. Maybe you could try to use [`partialize`](https://github.com/pmndrs/zustand/wiki/Persisting-the-store's-data#partialize) to reduce the amount of data you're storing?
