### ISSUE TITLE
Devtools seems to be broken in 3.6.6 onwards

### ISSUE THREAD

**Issue by dsacramone** [pmndrs/zustand#705]
ISSUE:
Devtools middleware seems to be broken from 3.6.6+ onwards.

REPRODUCE:
1. Go here: https://codesandbox.io/s/zustand-devtools-oddities-i6rrb?file=/src/chat.store.js
-- currently set at zustand version 3.6.7
-- view devtools. You will see that all actions are "anonymous".

2. Change dependency to 3.6.5, for zustand. (left side under "Dependencies", select zustand and update from dropdown).
-- view devtools, seems to be working with a custom "name" passed. 

3. Change dependency to 3.6.6, for zustand. (left side under "Dependencies", select zustand and update from dropdown).
-- view devtools, You will see that all actions are "anonymous"

3.6.6 seems to have introduced a breaking change.

**Comment by dai-shi** [comment]
@devanshj Can you take a look, please?

**Comment by devanshj** [comment]
This is an intended change, quoting from the PR #675...

> 1. **No more prefixing:** If you check the git history we used to prefix names/actions because we didn't used to pass the name to `connect` like so `connect({ name })` hence prefixing was needed because all zustand stores would show up in the same store instance. But later we started passing the `name` and that creates separate instances (which means separate action log and state) for each zustand store. But whoever made the change didn't realise that now we no longer need the prefixing, so hence we're removing it now.

Okay so let me elaborate on this. Long back all zustand stores had the same devtools instance meaning they shared the same action log. Hence we used to prefix the actions. But after we started creating a different instance (in #145) for each store they no longer shared the same action log, but we forgot to stop prefixing. Before this rewrite prefixing was redundant as all actions in the log have the same prefix. So this rewrite fixing that and we stop prefixing. If you want to see what devtools instance you're working on you can see at the top right dropdown (note it still reads "ACTION-TEST: " in the latest version).

In addition to this we also changed the anonymous action type from "action" to "anonymous", this is also an intended change as stated in the PR

> User can pass a `anonymousActionType` option to customize the action type logged in the devtools, by default it is "anonymous" previously it was "setState" or "action" (I think it's nice to have this option and also anonymous is a better default name but if wanted can be reverted)

So if you prefer some other name you can pass a `anonymousActionType` option.

Because of these two changes the actions change from "ACTION-TEST: > action" to "anonymous", which is intended. I hope I've made myself clear.

**Comment by omidantilong** [comment]
Hey, I've been playing with zustand for the last few days and really like it <3 But this issue has tripped me up a few times, so wondering if you could please clarify..! 

On this page https://github.com/pmndrs/zustand/wiki/Splitting-the-store-into-separate-slices there is an example of how to split a single store into multiple slices. Functionally it works as expected, but when wiring zustand up to redux devtools, all i ever see logged is "anonymous" (or whateveri pass as `anonymousActionType`).

I'd hoped zustand would log the name of the function in the slice that called `set`, or otherwise have some way of naming actions to help with debugging etc. Am I using it wrong? As far as I understand, even I had multiple stores instead of multiple slices, I'd still only be able to set the name of the store itself. The `set` function would not be logged.

Thankyou for your great work on this project and for having the best landing page I've seen in a while! :)

**Comment by devanshj** [comment]
I'm glad you're liking it! You can pass the action name in the third parameter of `set` (the second one is for replacing state).

```diff
- eatFish: () => set((prev) => ({ fishes: prev.fishes > 1 ? prev.fishes - 1 : 0}))
+ eatFish: () => set((prev) => ({ fishes: prev.fishes > 1 ? prev.fishes - 1 : 0}), false, "eatFish")
```

And now you'll be able to see "eatFist" in the action log. I think that'll resolve your issue.

I checked the documentation and I guess this isn't documented? I was under impression that it is, if that's the case then it should be documented.

**Comment by omidantilong** [comment]
Wonderful thankyou @devanshj . I've created a PR with an update to the readme for that. 

Quick aside - is this behaviour going to be maintained going into v4?

**Comment by devanshj** [comment]
Thanks for the PR. And yes this will be preserved in v4, it's not going anywhere.

**Comment by devanshj** [comment]
I think we can close this?

**Comment by dai-shi** [comment]
Hope to get a response from @dsacramone, but let's close for now.

**Comment by yekver** [comment]
It seems like the typescript `SetState` type are broken and and [doesn't know about the third parameter](https://github.com/pmndrs/zustand/blob/c319075d8c152b59054de78ca6051e3d22b7c62f/src/vanilla.ts#L36-L37) at all.

**Comment by dai-shi** [comment]
The middleware will override the type:
https://github.com/pmndrs/zustand/blob/0ba3c240078cf61792a4b13ff11d774ecca70a0a/src/middleware/devtools.ts#L29

It just works in a simple use case:
https://github.com/pmndrs/zustand/blob/0ba3c240078cf61792a4b13ff11d774ecca70a0a/tests/middlewareTypes.test.tsx#L130

In some cases with many middleware, you need to explicitly type store:
https://github.com/pmndrs/zustand/blob/0ba3c240078cf61792a4b13ff11d774ecca70a0a/tests/middlewareTypes.test.tsx#L251

We are trying to fix this explicit typing issue in v4.

**Comment by ZeroPie** [comment]
Still showing anonymous as of  "zustand": "^4.0.0-rc.1"
![Screenshot 2022-06-02 at 16 11 21](https://user-images.githubusercontent.com/8741666/171739012-07846182-015b-47fc-b070-092ad57d782e.png)
![Screenshot 2022-06-02 at 16 11 34](https://user-images.githubusercontent.com/8741666/171739046-058bb281-29c0-4f25-9b08-b3fd6174b827.png)

**Comment by piotr-cz** [comment]
Still broken in v5.0.1
