### ISSUE TITLE
Demo link. Errors in the console. 

### ISSUE THREAD

**Issue by young-healer** [pmndrs/zustand#747]
Please change 'class' to 'className'

Thank you.

**Comment by dai-shi** [comment]
Hi, the latest demo is deployed at: https://zustand-demo.pmnd.rs/
How is it?

**Comment by young-healer** [comment]
@dai-shi Hi, thank you for the quick answer, looks like there are a lot of re-renders 
![image](https://user-images.githubusercontent.com/37142332/148992185-7b0f421c-6247-445b-9220-b38b49dabf3f.png)

**Comment by DanielPower** [comment]
I'm not seeing the WebGL warnings, but I am seeing the `class` error.

**Comment by dai-shi** [comment]
Fixed the demo link in readme. ☝️

**Comment by DanielPower** [comment]
Looks like the class name issue has been solved :)

I do have to comment on the new demo though. Although it's pretty, all the ThreeJS code really bloats the main source file, and in my opinion makes the demo less effective at showing the simplicity of Zustand. In my opinion it would be better to pull the Canvas code including the definition of Scene into a separate file, so that App.js can focus on showing the usage of Zustand.

**Comment by dai-shi** [comment]
Yeah, basically the demo is not for reading the code.
Should I replace the link with `https://zustand-demo.pmnd.rs/`?

If you would like to refactor it feel free to send a PR.

**Comment by DanielPower** [comment]
This issue should be safe to close now.
