### ISSUE TITLE
Unable to view store in redux devtools

### ISSUE THREAD

**Issue by Nate-Wilkins** [pmndrs/zustand#899]
Hi!

I seem to have a problem linking the redux dev tools with zustand.

My setup is as follows:
```
import { devtools } from 'zustand/middleware';

export type State = {
  // State
  requests: Map<string, boolean>;

  // Actions
  storeRequest: (key: string) => void;
};

export const useStore = create<State>(
  devtools(
    (set): State => ({
      // State
      requests: new Map<string, boolean>(),

      // Actions
      storeRequest: (key: string) =>
        set(
          produce<State>(state => {
            state.requests.set(key, true);
          }),
        ),
    }),
  ),
);
```

![image](https://user-images.githubusercontent.com/2957868/162521261-83f655ec-9e55-4668-ac0d-dbdc470b8732.png)

When I augment state with `storeRequest` the state is not updated in redux devtools.
But is set internally in the store.

Is there something that I'm missing or is this broken in the latest release? (I'm using `3.7.2`)

**Comment by dai-shi** [comment]
Not sure, but I wonder if you still have the same behavior without immer and Map.

**Comment by jose-vale** [comment]
I believe that if you pass `{ serialize: true }` as the second argument of devtools() it should work, but it will apply to everything. If you only need it for maps you could use:
```javascript
{
    serialize: {
        options: {
            map: true
        }
    } as any
}
```
The `as any` is necessary due to an issue with the typing in devtools, correct me if I'm wrong @dai-shi.

The [README](https://github.com/pmndrs/zustand/blob/197e5d41993b0e3ad6ebef9a7e6a9161753072f1/readme.md?plain=1#L355) mentions this, but the info is not up-to-date. Might look into fixing the typing issue and updating the README to be a bit more clear.

**Comment by dai-shi** [comment]
closing as stale.
