### ISSUE TITLE
devtools: Application state or actions payloads are too large making Redux DevTools serialization slow

### ISSUE THREAD

**Issue by Jerryhu1** [pmndrs/zustand#926]
I have a store with a large map in it that is being serialized by devtools. I get the warning: 
```
Application state or actions payloads are too large making Redux DevTools serialization slow and consuming a lot of memory. 
See https://git.io/fpcP5 on how to configure it.
```
I'm aware that I can simply disable serialization, but there are other maps in the store which I want to get serialized. 
The link suggests to make use of a `stateSanitizer`. Is there a way to do this in zustand devtools?

**Comment by Jerryhu1** [comment]
I assume this is not possible yet? Then I can attempt at a PR to add it.

**Comment by dai-shi** [comment]
@Aslemammad @devanshj any idea on this?

**Comment by dai-shi** [comment]
possibly related? #716

**Comment by Aslemammad** [comment]
I don't have so much clue about this issue, @devanshj is better than me I guess in this!

**Comment by devanshj** [comment]
I think we can check if `stateSanitizer` is to be implemented by us or the extension handles it. The way to do that is try doing this...

```ts
create(devtools(() => ({ actual: "data" }), {
  // @ts-ignore
  stateSanitizer: () => ({ hello: "world" })
})
```

If the redux-devtool now shows `{ hello: "world" }` as the data then it means the extension handles it for us and we just have to expose `stateSanitizer` in our types.

If the redux-devtool doesn't show `{ hello: "world" }` (and shows `{ actual: "data" }`) then it means we have to support `stateSanitizer` from our side. Which is easy too, all you have to do is write `stateSanitizer(state)` instead of `state` when you send the state to extension (and default `stateSanitizer` is `s => s`).

(This check can be done for all options and if the option is handled by the extension we just have to expose it in our types)

**Comment by dai-shi** [comment]
Let's merge the discuss into #716.
