### ISSUE TITLE
createContext creates wrong typescript for useStoreApi().subscribe

### ISSUE THREAD

**Issue by wuifdesign** [pmndrs/zustand#998]
When using createContext and wanting to subscribe to changes i can use the old style (listener, selector, equalityFn) but i will end up with a deprecated warning. 

If i change it to the new `subscribeWithSelector` it will work fine, but the typescript will show an error as it still wants the old format to be used (listener, selector, equalityFn) instead of the new (selector, listener, equalityFn)

![error](https://user-images.githubusercontent.com/5678318/172486803-f1dc8d0c-7120-4db4-9205-7472e198b099.png)

```ts
import create from 'zustand'
import createContext from 'zustand/context'
import { subscribeWithSelector } from 'zustand/middleware'
import { useEffect } from 'react'

type TestStoreState = {
  readonly bears: number
  increase: (by: number) => void
}

const { Provider, useStoreApi } = createContext<TestStoreState>()

const createStore = () =>
  create(
    subscribeWithSelector<TestStoreState>((set) => ({
      bears: 0,
      increase: (by) => set((state) => ({ bears: state.bears + by }))
    }))
  )

const App = () => (
  <Provider createStore={createStore}>
    <Test />
  </Provider>
)

const Test: React.FC = () => {
  const storeApi = useStoreApi()

  useEffect(
    () =>
      storeApi.subscribe(
        (state) => state.bears,
        (bears) => {
          console.log(bears)
        }
      ),
    [storeApi]
  )

  return null
}
```

**Comment by wuifdesign** [comment]
ok, found it by myself. in case someone else needs this:

```ts

const { Provider, useStoreApi } =
  createContext<
    TestStoreState,
    UseBoundStore<TestStoreState, Mutate<StoreApi<TestStoreState>, [['zustand/subscribeWithSelector', never]]>>
  >()
```

**Comment by making3** [comment]
For Zustand v4+, `createContext` is deprecated (and removed in 5+), so `React.createContext` is needed instead. Otherwise, it's effectively the same without the first type arg (I found this a little hard to find in the docs, so thank you, @wuifdesign ).

```
import React from 'react';
import { type Mutate, type StoreApi } from 'zustand';

export interface SomeState {
    someValue: string
    setSomeValue(newValue: string): void;
}

type StoreApiWithSubscribeWithSelector<T> = Mutate<StoreApi<T>, [['zustand/subscribeWithSelector', never]]>;
const StoreContext = React.createContext<StoreApiWithSubscribeWithSelector<SomeState> | null>(null);
```

It's sort of documented in the [TypeScript Guide](https://zustand.docs.pmnd.rs/guides/typescript#middleware-that-changes-the-store-type) but not overly clear IMO (I'm sure using context here is less common)

I left out `UseBoundStore` as well for mine (I think it's only needed for [auto generating selectors](https://zustand.docs.pmnd.rs/guides/auto-generating-selectors)).
